    +------------------+              +-----------------------+
    |      Client      |              |      Express App      |
    +------------------+              +-----------------------+
           |                               |
           | HTTP Requests                 |
           |                               |
           V                               V
    +------------------+              +-----------------------+
    |      Routes      |              |   Controllers (CRUD)  |
    +------------------+              +-----------------------+
           |                               |
           | Route Handling                |
           |                               |
           V                               V
    +------------------+              +-----------------------+
    |      Models      |              |      Database (MongoDB)|
    +------------------+              +-----------------------+
           |                               |
           | Data Manipulation             |
           |                               |
           V                               V
    +------------------+              +-----------------------+
    |   Person Model   |              |  Person Collection    |
    +------------------+              +-----------------------+
           |                               |
           | Data Structure                |
           |                               |
           V                               V
    +------------------+              +-----------------------+
    |     Attributes   |              |    Database Records   |
    +------------------+              +-----------------------+
           |                               |
           |                               |
           |                               |
           V                               V
    +------------------+              +-----------------------+
    |      name        |              |        name           |
    |                  |              |                       |
    +------------------+              +-----------------------+
